hcctl: improve error handling for missing token
Rather than doing this

➜ hcctl list
thread 'main' panicked at 'HEALTHCHECKS_TOKEN must be set to run monitor: NotPresent', hcctl/src/main.rs:61:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

We now do

~ ➜ hcctl list
Error: HEALTHCHECKS_TOKEN must be set to run hcctl

Signed-off-by: Harsh Shandilya <me@msfjarvis.dev>