monitor: improve error handling for missing token
Rather than doing this

➜ healthchecks-monitor
thread 'main' panicked at 'HEALTHCHECKS_CHECK_ID must be set to run monitor: NotPresent', monitor/src/main.rs:19:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

We now do

➜ healthchecks-monitor
Error: HEALTHCHECKS_CHECK_ID must be set to run monitor

Signed-off-by: Harsh Shandilya <me@msfjarvis.dev>